### ISSUE TITLE
Bare-metal deployment

### ISSUE THREAD

**Issue by nhma20** [tensil-ai/tensil#25]
Hi,

How would I go about deploying the tensil accelerator in bare-metal (i.e. without Pynq or Petalinux) on a board like the Ultra96 or PYNQ-Z1? Is it feasible at all? I have been working with FINN (https://github.com/Xilinx/finn) in bare-metal previously and would like to try and compare the two frameworks.

Best regards,
Nicolaj

**Comment by tdb-alcorn** [comment]
We have an embedded driver that can be used in bare-metal deployments. There is an example of how to do it for Ultra96v2 here: https://github.com/tensil-ai/tensil/tree/main/drivers/embedded/ultra96v2

We'll release a tutorial on how to use it in the future, but for now feel free to ping me on our Discord and I can help you get it running.

Discord link: https://discord.gg/TSw34H3PXr

Does that help?

**Comment by alex-ssom** [comment]
Hi, 

We are interested by running bare-metal as well. 

Would you happen to have an ETA on the tutorial?

Thanks,
Alex

**Comment by petrohi** [comment]
It is released https://www.tensil.ai/docs/tutorials/speech-robot-part1/

Enjoy!
