### ISSUE TITLE
Is there tutorial build tensil binary from source

### ISSUE THREAD

**Issue by minisparrow** [tensil-ai/tensil#31]
Hi, I want to build project from source, is there some tutorial for that? thanks

**Comment by tdb-alcorn** [comment]
You can run `./mill '{rtl,tools}.assembly'` to generate the rtl and compiler assemblies, they will be output at `rtl/assembly.dest/out.jar` and `tools/assembly.dest/out.jar` respectively. Copy the assemblies to `/opt/tensil/` like so 

```
mkdir -p /opt/tensil/
cp rtl/assembly.dest/out.jar /opt/tensil/rtl.jar
cp tools/assembly.dest/out.jar /opt/tensil/tools.jar
```

You can then add [this file](https://github.com/tensil-ai/tensil/blob/main/docker/bin/tensil) to `/usr/local/bin` to enable the `tensil compile|rtl` command line tool.

Does this help?

**Comment by minisparrow** [comment]
Thanks for reply, when i build using ./mill rtl.assemply, there is error reported as follows: 
```
[error]  tensil/common/src/tensil/ArchitectureDataType.scala:43:27: value readNBytes is not a member of java.io.DataInputStream
[error]     base.fromBytes(stream.readNBytes(base.sizeBytes))
```

**Comment by minisparrow** [comment]
> Thanks for reply, when i build using ./mill rtl.assemply, there is error reported as follows:
> 
> ```
> [error]  tensil/common/src/tensil/ArchitectureDataType.scala:43:27: value readNBytes is not a member of java.io.DataInputStream
> [error]     base.fromBytes(stream.readNBytes(base.sizeBytes))
> ```

thanks @tdb-alcorn , I find this error mainly because i use java 18, when i use java 19, it build sucess. Thanks very much.

**Comment by tdb-alcorn** [comment]
Glad it's working now! We use OpenJDK 11 from Azul for development, so you should be able to get things running with that. 
https://github.com/tensil-ai/tensil#additional-setup-steps

If you have `asdf` tool version manager installed, you can point it at this https://github.com/tensil-ai/tensil/blob/main/.tool-versions.

**Comment by minisparrow** [comment]
> Glad it's working now! We use OpenJDK 11 from Azul for development, so you should be able to get things running with that. https://github.com/tensil-ai/tensil#additional-setup-steps
> 
> If you have `asdf` tool version manager installed, you can point it at this https://github.com/tensil-ai/tensil/blob/main/.tool-versions.

Many Thanks. sorry I have another question. I can run `./mill __.test` for all testsuit, but if I want to run an unittest for a specific module, such as  Accumulator Module, how could i make this test. Thanks again :)

**Comment by petrohi** [comment]
To run specific test, for example `SamplerSpec`:

```
./mill rtl.test.testOnly tensil.tcu.SamplerSpec
```

Also if you want vcd files (waveforms) to be generated:

```
./mill rtl.test.testOnly tensil.tcu.SamplerSpec -- -DwriteVcd=true
```

**Comment by minisparrow** [comment]
> To run specific test, for example `SamplerSpec`:
> 
> ```
> ./mill rtl.test.testOnly tensil.tcu.SamplerSpec
> ```
> 
> Also if you want vcd files (waveforms) to be generated:
> 
> ```
> ./mill rtl.test.testOnly tensil.tcu.SamplerSpec -- -DwriteVcd=true
> ```

thanks very much, that's really big help for me. Thank you petrohi. :)
