### ISSUE TITLE
Key not found: Identity:0

### ISSUE THREAD

**Issue by B-Willems** [tensil-ai/tensil#47]
I made a tensorflow model and converted it to .onnx file using tf2onnx. 

`!python -m tf2onnx.convert --saved-model "my_modeltwo" --output "model.onnx"`

When trying to generate the .tdata, .tprog and .tmodel files only the first two are generated. When executing the command i get following exception:
![image](https://user-images.githubusercontent.com/15821611/165518034-7f15b0a7-c958-4668-9834-ae53f6a1bc37.png)

My tensorflow network:
`def create_model(optimizer):
    input_img   = Input(shape=(75, 75, 4), name="X_img")

    cnn = Conv2D(16, kernel_size=(3,3), activation = "relu")(input_img)
    cnn = MaxPooling2D((2,2))(cnn)
    cnn = Dropout(0.1) (cnn)

    cnn = Conv2D(32, kernel_size=(3,3), activation = "relu")(cnn)
    cnn = MaxPooling2D((2,2))(cnn)
    cnn = Dropout(0.1)(cnn)

    cnn = Conv2D(64, kernel_size=(3,3), activation = "relu")(cnn)
    cnn = MaxPooling2D((2,2))(cnn)
    cnn = Dropout(0.1)(cnn)  

    cnn = Conv2D(128, kernel_size=(3,3), activation = "relu")(cnn)
    cnn = Conv2D(128, kernel_size=(3,3), activation = "relu") (cnn)
    cnn = MaxPooling2D((2,2))(cnn)
    cnn = Dropout(0.1)(cnn)  
    
    cnn = Flatten()(cnn)

    dense = Dense(64, activation="relu")(cnn)
    dense = Dense(64, activation="relu") (dense)
    dense = Dense(64, activation="relu") (dense)

    output = Dense(1, activation="sigmoid")(dense)

    model = Model(input_img, output)

    model.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])
    return model

model = create_model(optimizer = Adam())
model.summary()`

My onnx model: https://drive.google.com/file/d/1-lVduUVw8qdOREVN3mjex2fGQziUVPL4/view?usp=sharing

**Comment by tdb-alcorn** [comment]
That's a separate thing - matmul layers are supported but sometimes the ONNX conversion does an odd renaming. @petrohi  do you recall what the fix was for this?

**Comment by petrohi** [comment]
Tensil ONNX compiler does not support `MatMul`. It supports `Gemm`, which is a combination of `MatMul` and `Add` (matrix multiply with bias). To make the TF-to-ONNX converter produce `Gemm` you need to freeze dimensions by specifying input shape. For your model it looks like you'd need to add `--inputs X_img:0[1,75,75,4]` argument. We also recommend using ONNX 11 opset (`--opset 11`).

**Comment by B-Willems** [comment]
The --inputs X_img:0[1,75,75,4] argument does not seem to work. It throws an error: 
`AssertionError: X_img is not in graph`

error log listed below (sorry for image but code block didn't format right):

![image](https://user-images.githubusercontent.com/15821611/165589617-02e3fe53-bf12-4342-bd01-4e3ef4984ace.png)


perhaps this question is better asked on the tf2onnx github page though? But it seems you have lots of experience with this sort of thing.

**Comment by petrohi** [comment]
Please check what is the name of the input node in your TF model (in Netron) and try using it instead of `X_Img`.

**Comment by B-Willems** [comment]
Alright, in netron the name of the input node was also X_img. However when in remove the `name = 'X_img'` argument from the input layer and execute following command it exports correctly, with _gemm_ layers instead of _matmul_ and _add_ layers. Thank you very much for the support. I'll close this issue since the problem is solved.

**Comment by thomasjeff0420** [comment]
Hi, I am facing this problem when trying to compile my model to tensil. Could anyone help me, please!!!
![ảnh](https://github.com/tensil-ai/tensil/assets/134514490/e4254529-7f78-49ac-89dc-762349540569)
![ảnh](https://github.com/tensil-ai/tensil/assets/134514490/6f2aa4e3-0f0a-42d8-bde7-77c556388b40)
